### ISSUE TITLE
pull access denied for afl-blackbox and your other docker hubs

### ISSUE THREAD

**Issue by Chaos-Monkey-Island** [pentagridsec/5-AFL-suite-docker#1]
I logged into docker hub (docker login ) and then ran your builds as per your docs.  access denied -->
Step 1/8 : FROM afl-blackbox AS afl-demo
pull access denied for afl-blackbox, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by floyd-fuh** [comment]
Hi! Did you try
`﻿FROM pentagrid/afl-blackbox AS afl-demo`
yet? I think that might be it. Try running this on the command line first:
`docker pull pentagrid/afl-blackbox`
Does that work?
